platform_dbt:
  target: dev
  outputs:
    dev:
      type: postgres
      host: postgres-warehouse
      port: 5432
      user: svc_dwh
      password: svc_dwh
      dbname: warehouse
      schema: bronze
      threads: 2
    snowflake:
      type: snowflake
      account: XXLIRRB-PG74236
      user: svc_terraform
      password: TerraformPass123!
      role: ACCOUNTADMIN
      warehouse: PLATFORM_WH
      database: PLATFORM_DB
      schema: SILVER
      threads: 2
